name: getx_miscellanous
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  animated_checkmark: ^3.1.0
  audioplayers: ^6.5.1
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  flex_seed_scheme: ^3.5.1
  flutter:
    sdk: flutter
  flutter_m3shapes: ^1.0.0+1
  flutter_rounded_progress_bar: ^0.3.2
  get: 5.0.0-release-candidate-9.3.2
  just_audio: ^0.9.46
  just_audio_windows: ^0.2.2
  #liquid_progress_indicator: ^0.4.0
  liquid_glass_easy: ^1.0.0
  mix: ^1.7.0
  package_info_plus: ^9.0.0
  pinput: ^5.0.1
  settings_ui: ^2.0.2
  signals: ^6.2.0
  star_menu: ^4.0.1
  statemachine: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/images/background/
    - assets/audio/
    - assets/licenses/
  fonts:
    - family: OpenSans
      fonts: 
        - asset: assets/fonts/OpenSans.ttf
    - family: KodeMono
      fonts: 
        - asset: assets/fonts/KodeMono.ttf
    - family: StardosStencil
      fonts: 
        - asset: assets/fonts/StardosStencil.ttf    
